#!/usr/bin/env node
/*
 * Builds the blog listing pages and the sitemap from project-docs/posts.json.
 *
 *   node project-docs/build-blog.js
 *
 * Reads  : project-docs/posts.json, dist/blogs-template.html
 * Writes : dist/blogs.html, dist/blogs-2.html, ... and dist/sitemap.xml
 *
 * Plain Node, no dependencies. Cards are written into the HTML at build time
 * so crawlers see them in the raw source - nothing is rendered client-side.
 */
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const DIST = path.join(ROOT, "dist");
const POSTS_FILE = path.join(__dirname, "posts.json");
const TEMPLATE_FILE = path.join(DIST, "blogs-template.html");

const PER_PAGE = 9;
const SITE = "https://sixthsensemma.com";

/* Pages the sitemap should carry besides the posts and the listing. */
const STATIC_PAGES = [
  { loc: "/", priority: "1.0", changefreq: "weekly" },
  { loc: "/adult-bjj-classes/", priority: "0.8", changefreq: "monthly" },
  { loc: "/adult-muay-thai-classes/", priority: "0.8", changefreq: "monthly" },
  { loc: "/kids-bjj-classes/", priority: "0.8", changefreq: "monthly" },
  { loc: "/teen-bjj-classes/", priority: "0.8", changefreq: "monthly" },
  { loc: "/teen-muay-thai-classes/", priority: "0.8", changefreq: "monthly" }
];

const escapeHtml = s =>
  String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

/* Page 1 keeps the clean /blogs/ URL; later pages are blogs-2.html onward. */
const pageFile = n => (n === 1 ? "blogs.html" : `blogs-${n}.html`);
const pageUrl = n => (n === 1 ? `${SITE}/blogs/` : `${SITE}/blogs/page/${n}/`);

function cardHtml(post) {
  return `        <article class="bl-card">
          <a class="bl-card-link" href="${escapeHtml(post.slug)}.html">
            <img src="${escapeHtml(post.image)}" alt="${escapeHtml(post.title)}" width="360" height="250" loading="lazy" decoding="async">
            <div class="bl-card-body">
              <h2 class="bl-card-title">${escapeHtml(post.title)}</h2>
            </div>
          </a>
        </article>`;
}

function paginationHtml(current, total) {
  if (total < 2) return "";
  const items = [];

  if (current > 1) {
    items.push(`          <a class="bl-page-arrow" href="${pageFile(current - 1)}" rel="prev" aria-label="Previous page">&larr;</a>`);
  }
  for (let n = 1; n <= total; n++) {
    items.push(
      n === current
        ? `          <span class="bl-page is-current" aria-current="page">${n}</span>`
        : `          <a class="bl-page" href="${pageFile(n)}">${n}</a>`
    );
  }
  if (current < total) {
    items.push(`          <a class="bl-page-arrow" href="${pageFile(current + 1)}" rel="next" aria-label="Next page">&rarr;</a>`);
  }

  return `      <nav class="bl-pagination" aria-label="Blog pages">
${items.join("\n")}
      </nav>`;
}

function headLinks(current, total) {
  const lines = [`<link rel="canonical" href="${pageUrl(current)}">`];
  if (current > 1) lines.push(`<link rel="prev" href="${pageUrl(current - 1)}">`);
  if (current < total) lines.push(`<link rel="next" href="${pageUrl(current + 1)}">`);
  return lines.join("\n");
}

function buildSitemap(posts, totalPages) {
  const today = new Date().toISOString().slice(0, 10);
  const urls = [];

  for (const p of STATIC_PAGES) {
    urls.push({ loc: SITE + p.loc, lastmod: today, changefreq: p.changefreq, priority: p.priority });
  }
  for (let n = 1; n <= totalPages; n++) {
    urls.push({ loc: pageUrl(n), lastmod: today, changefreq: "weekly", priority: n === 1 ? "0.9" : "0.5" });
  }
  for (const post of posts) {
    urls.push({ loc: `${SITE}/${post.slug}/`, lastmod: post.date, changefreq: "monthly", priority: "0.7" });
  }

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls
  .map(
    u => `  <url>
    <loc>${u.loc}</loc>
    <lastmod>${u.lastmod}</lastmod>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`
  )
  .join("\n")}
</urlset>
`;
}

function main() {
  const posts = JSON.parse(fs.readFileSync(POSTS_FILE, "utf8"));
  const template = fs.readFileSync(TEMPLATE_FILE, "utf8");

  for (const marker of ["<!-- POSTS -->", "<!-- PAGINATION -->", "<!-- HEAD-LINKS -->"]) {
    if (!template.includes(marker)) {
      console.error(`Template is missing the ${marker} marker. Nothing written.`);
      process.exit(1);
    }
  }

  /* Newest first. */
  posts.sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0));

  const totalPages = Math.max(1, Math.ceil(posts.length / PER_PAGE));
  const written = [];

  for (let n = 1; n <= totalPages; n++) {
    const slice = posts.slice((n - 1) * PER_PAGE, n * PER_PAGE);
    const cards = [
      "        <!-- Generated by project-docs/build-blog.js from posts.json - do not edit by hand. -->",
      ...slice.map(cardHtml)
    ].join("\n");

    const html = template
      .replace("<!-- HEAD-LINKS -->", headLinks(n, totalPages))
      .replace("<!-- POSTS -->", cards)
      .replace("<!-- PAGINATION -->", paginationHtml(n, totalPages));

    const file = path.join(DIST, pageFile(n));
    fs.writeFileSync(file, html);
    written.push({ file: pageFile(n), posts: slice.length });
  }

  /* Remove listing pages left over from a previous, longer run. */
  for (const name of fs.readdirSync(DIST)) {
    const m = name.match(/^blogs-(\d+)\.html$/);
    if (m && Number(m[1]) > totalPages) {
      fs.unlinkSync(path.join(DIST, name));
      written.push({ file: name, posts: "removed (stale)" });
    }
  }

  fs.writeFileSync(path.join(DIST, "sitemap.xml"), buildSitemap(posts, totalPages));

  console.log(`${posts.length} post(s), ${PER_PAGE} per page, ${totalPages} page(s).\n`);
  for (const w of written) console.log(`  wrote dist/${w.file}  (${w.posts} cards)`);
  console.log("  wrote dist/sitemap.xml\n");
  console.log("Order, newest first:");
  posts.forEach((p, i) => console.log(`  ${i + 1}. ${p.date}  ${p.title}`));
}

main();
